version: '3'
services:
  strapi:
    image: codebunny/strapi
    restart: always
    container_name: strapi-v4
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: production
      JWT_SECRET: wd4SgxPuxW3vNxSvD3k5YA==
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: supersecret
      PUBLIC_URL: http://strapi.internal:1337
      IS_PROXIED: true
      DATABASE_SSL: false # boolean for SSL.
    # volumes:
    #   - app:/srv/app # create a new project in app volume
  mariadb:
    restart: always
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - data:/var/lib/mariadb/data
    expose:
      - 3306
    logging:
      driver: none
volumes:
  data:
  app:
